#!/bin/bash

build() {
    for bin in /usr/bin/dulge-*; do
        add_binary "$bin"
    done

    for key in /var/db/dulge/keys/*; do
        add_file "$key"
    done

    for conf in /usr/share/dulge.d/*; do
        add_file "$conf"
    done
}

help() {
    cat <<HELPEOF
This hook will add dulge to recover broken voidlinux installations.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
