# Cross build profile for ARMv8.

DULGE_TARGET_MACHINE="aarch64-musl"
DULGE_TARGET_QEMU_MACHINE="aarch64"
DULGE_CROSS_TRIPLET="aarch64-linux-musl"
DULGE_CROSS_CFLAGS="-march=armv8-a"
DULGE_CROSS_CXXFLAGS="$DULGE_CROSS_CFLAGS"
DULGE_CROSS_FFLAGS="$DULGE_CROSS_CFLAGS"
DULGE_CROSS_RUSTFLAGS="--sysroot=${DULGE_CROSS_BASE}/usr"
DULGE_CROSS_RUST_TARGET="aarch64-unknown-linux-musl"
DULGE_CROSS_ZIG_TARGET="aarch64-linux-musl"
DULGE_CROSS_ZIG_CPU="baseline"
