# Cross build profile for i686 and Musl libc.

DULGE_TARGET_MACHINE="i686-musl"
DULGE_TARGET_QEMU_MACHINE="i386"
DULGE_CROSS_TRIPLET="i686-linux-musl"
DULGE_CROSS_CFLAGS="-march=i686"
DULGE_CROSS_CXXFLAGS="$DULGE_CROSS_CFLAGS"
DULGE_CROSS_FFLAGS="$DULGE_CROSS_CFLAGS"
DULGE_CROSS_RUSTFLAGS="--sysroot=${DULGE_CROSS_BASE}/usr"
DULGE_CROSS_RUST_TARGET="i686-unknown-linux-musl"
DULGE_CROSS_ZIG_TARGET="i686-linux-musl"
DULGE_CROSS_ZIG_CPU="baseline"
