# Cross build profile for i686 GNU.

DULGE_TARGET_MACHINE="i686"
DULGE_TARGET_QEMU_MACHINE="i386"
DULGE_CROSS_TRIPLET="i686-pc-linux-gnu"
DULGE_CROSS_CFLAGS="-march=i686"
DULGE_CROSS_CXXFLAGS="$DULGE_CROSS_CFLAGS"
DULGE_CROSS_FFLAGS="$DULGE_CROSS_CFLAGS"
DULGE_CROSS_RUSTFLAGS="--sysroot=${DULGE_CROSS_BASE}/usr"
DULGE_CROSS_RUST_TARGET="i686-unknown-linux-gnu"
DULGE_CROSS_ZIG_TARGET="i386-linux-gnu"
DULGE_CROSS_ZIG_CPU="_i686+sse2"
