# Cross build profile for PowerPC.

DULGE_TARGET_MACHINE="ppc-musl"
DULGE_TARGET_QEMU_MACHINE="ppc"
DULGE_CROSS_TRIPLET="powerpc-linux-musl"
DULGE_CROSS_CFLAGS="-mtune=G4"
DULGE_CROSS_CXXFLAGS="$DULGE_CROSS_CFLAGS"
DULGE_CROSS_FFLAGS="$DULGE_CROSS_CFLAGS"
DULGE_CROSS_RUSTFLAGS="--sysroot=${DULGE_CROSS_BASE}/usr"
DULGE_CROSS_RUST_TARGET="powerpc-unknown-linux-musl"
DULGE_ZIG_TARGET="powerpc-linux-musl"
DULGE_ZIG_CPU="baseline"
