# Cross build profile for riscv64 and Musl libc.

DULGE_TARGET_MACHINE="riscv64-musl"
DULGE_TARGET_QEMU_MACHINE="riscv64"
DULGE_CROSS_TRIPLET="riscv64-linux-musl"
DULGE_CROSS_CFLAGS="-march=rv64imafdc"
DULGE_CROSS_CXXFLAGS="$DULGE_CROSS_CFLAGS"
DULGE_CROSS_FFLAGS="$DULGE_CROSS_CFLAGS"
DULGE_CROSS_RUSTFLAGS="--sysroot=${DULGE_CROSS_BASE}/usr"
DULGE_CROSS_RUST_TARGET="riscv64gc-unknown-linux-musl"
DULGE_CROSS_ZIG_TARGET="riscv64-linux-musl"
DULGE_CROSS_ZIG_CPU="baseline"
