# Cross build profile for x86_64 and Musl libc.

DULGE_TARGET_MACHINE="x86_64-musl"
DULGE_TARGET_QEMU_MACHINE="x86_64"
DULGE_CROSS_TRIPLET="x86_64-linux-musl"
DULGE_CROSS_CFLAGS="-mtune=generic"
DULGE_CROSS_CXXFLAGS="$DULGE_CROSS_CFLAGS"
DULGE_CROSS_FFLAGS="$DULGE_CROSS_CFLAGS"
DULGE_CROSS_RUSTFLAGS="--sysroot=${DULGE_CROSS_BASE}/usr"
DULGE_CROSS_RUST_TARGET="x86_64-unknown-linux-musl"
DULGE_CROSS_ZIG_TARGET="x86_64-linux-musl"
DULGE_CROSS_ZIG_CPU="baseline"
