#!/bin/sh

# Ensure GIO_MODULE_DIR is not set so we don't load random things
# which may then get deleted (or their dependencies) and potentially segfault
/usr/bin/qemu-${DULGE_TARGET_QEMU_MACHINE}-static ${GIR_EXTRA_OPTIONS} \
			-L ${DULGE_CROSS_BASE} \
			-E LD_LIBRARY_PATH="${DULGE_CROSS_BASE}/usr/lib:.libs:${GIR_EXTRA_LIBS_PATH}" \
			-U GIO_MODULE_DIR \
			"$@"
