#!/bin/env/python

import os

Dirctory = [
           'acl', "attr","audit","autoconf",
            "automake","b43-fwcutter","jaguar-base", 
            "jaguar-devel","bash","binutils",
            "bison","brotil","btrfs-progs", 
            "bzip2", "ca-certificates", "nss",
            "coreutils","cracklib", "cryptsetup", 
            "curl","dash","db","db5.3",
            "dbus", "dbus-broker", 
            "debugedit","elfutils","lvm2",
            "dialog","diffutils","ding-libs",
            "dmraid","dnssec-anchors","dosfstools"
            "e2fsprogs","efivar","expat"
            "fakeroot","file","filesystem",
            "findutils","flex","gawk",
            "gc","gcc","gdbm"
            "gettext","glib2","glibc",
            "gmp","gnulib-l10n","gnupg",
            "gnutls","gpgme","gpm",
            "grep","groff","gssproxy",
            "guile","gzip","hdpam",
            "hwdata","iana-etc","icu",
            "inetutils","iprotue2","iptables",
            "iputils","iw","jansson",
            "jfsutils","json-c","kbd",
            "keyutils","kmod","krb5",
            "ldns","leancrypto","lemon",
            "less","lib32-gcc","lib32-glibc",
            "libaio","libarchive","libassuan",
            "libbpf","libcap","libcap-ng",
            "curl","libedit","libevent",
            "libffi","libgcrypt","libgpg-error",
            "libidn2","libinih","libisl",
            "libksba","libldap","libmicrohttpd",
            "libmnl","libmpc","libnetfilter_conntrack",
            "libnfnetlink","libnftnl","libnghttp2",
            "libnghttp3","libnl","libnsl",
            "libp11-kit","libpcap","libpipeline",
            "libpsl","libsasl","libseccomp",
            "libsecret","libssh2","libtasn1",
            "libtirpc","libtool","libunistring",
            "libusb","libverto","libxcrypt",
            "libxml2","licenses","links",
            "ps4-linux","ps4-linux-headers","ps4linuux-frimware",
            "ps4-linux-docs","lz4","lzo",
            "m4","make","man-db",
            "man-pages","mdadm","minizip",
            "mpdecimal","mpfr","nano",
            "ncurses","net-tools","nettle",
            "nfs-utils","nilfs-utils","npth",
            "nspr","nss","openldap",
            "openssh","openssl","openssl-1.1",
            "p11-kit","ps4","ps4-mirrorlist",
            "pam","pambase","patch",
            "pciutils","pcre","pcre2",
            "perl","pinentry","pkgconf",
            "popt","ppp","pptpclient",
            "procps-ng","psmisc","python",
            "audit","brotli","libcap-ng",
            "libseccomp","readline","rpcbind",
            "s-nail","sdparm","sed",
            "shadow","sqlite","sudo",
            "syslinux","systemd", "systemV","openrc","tar",
            "texinfo","thin-provisioning-tools","tpm2-tss",
            "tzdata","unixodbc","usbutils",
            "util-linux","vim","which",
            "wireless-regdb","wpa_supplicant","xfsprogs",
            "xz","zlib","zstd"
]

for items in Dirctory:
    os.mkdir(items)
